#!/bin/sh

savedtz=$(timedatectl | grep 'Time zone' | awk '{ print $3 }')

timedatectl || exit 1

timedatectl set-time "$(date +'%H:%M:%S')" || exit 1
sleep 2
timedatectl set-local-rtc 0 || exit 1
sleep 1
timedatectl set-local-rtc 1 || exit 1
sleep 1

timedatectl set-timezone America/New_York || exit 1
sleep 1
timedatectl set-timezone $savedtz || exit 1
sleep 1

timedatectl set-ntp 1 || exit 1
timedatectl set-ntp 0 || exit 1

timezones=$(timedatectl list-timezones) || exit 1

echo "$timezones" | grep -q '^Europe/Prague$' || exit 1
[ $(echo "$timezones" | wc -l) -gt 300 ] || exit 1
